baseURL: "https://toromuu.netlify.app"
languageCode: "en-us"
title: "Diego A. Toro Ramirez"
theme: hugo-profile

Paginate: 3
disqusShortname: gurusabarish
googleAnalytics: G-DWJJVE27WD

markup:
  goldmark:
    renderer:
      unsafe: true

Menus:
  main:
    - identifier: blog
      name: Blog
      title: Blog posts
      url: /blogs
      weight: 1

params:
  title: "Diego A. Toro Ramirez"
  description: Welcome to my personal Website
  # staticPath: ""  # The path to serve the static files from
  favicon: "/fav.png"

  theme:
    disableThemeToggle: false
    # defaultTheme: "light" # dark

  # font:
  #   fontSize: 1.5rem # default: 1rem
  #   fontWeight: 500 # default: 400
  #   lineHeight: 1 # default: 1.5
  #   textAlign: right # default: left

  # color preference
  # color:
  #   textColor:
  #   secondaryTextColor:
  #   backgroundColor:
  #   secondaryBackgroundColor:
  #   primaryColor:
  #   secondaryColor:

  #   darkmode:
  #     textColor:
  #     secondaryTextColor:
  #     backgroundColor:
  #     secondaryBackgroundColor:
  #     primaryColor:
  #     secondaryColor:

  # If you want to customize the menu, you can change it here
  # navbar:
  #   align: mx-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
  #   brandLogo: "/logo.png" # Logo for the brand | default is the favicon variable
  #   brandName: "Profile" # Brand name for the brand | default is the title variable

  #   menus:
  #     disableAbout: true
  #     disableExperience: true
  #     disableEducation: true
  #     disableProjects: true
  #     disableAchievements: true
  #     disableContact: true

  # Hero
  hero:
    enable: true
    intro: "Hi, my name is"
    title: "Diego."
    subtitle: "I build infraestructure in the Cloud"
    content: "I am a DevOps Engineer with a passion for Cloud and Automatition."
    image: /images/hero.jpg
    button:
      enable: true
      name: "Resume"
      url: "#"
    socialLinks:
      fontAwesomeIcons:
        - icon: fab fa-github
          url: https://github.com/toromuu
        - icon: fab fa-linkedin
          url: https://www.linkedin.com/in/diego-a-t-04726516b/

  # About
  about:
    enable: true
    title: "About Me"
    image: "/images/me.jpg"
    content: |-
      I am an enthusiast of this new era of technological innovations. I would like to say that I am already a engineer but I still have a long way to go, learning and having fun every day.

      I have a background in computer science and I am currently finishing a master's degree in cloud computing and high performance in Valencia.

      I am at a stage in my life where I have ambition to learn by putting into practice all my knowledge, innovate and develop solutions that change people's lives.
    
    skills:
      enable: true
      title: "Here are a few technologies I've been working with recently:"
      items:
        - "Kubernetes"
        - "Docker"
        - "Ansible"
        - "Terraform"
        - "AWS"
        - "Jenkins"
        - "Bash"
        - "PowerShell"
        - "VirtualBox"
        - "Vagrant"

  # Experience
  experience:
    enable: true
    items:
      - job: "DevOps Engineer"
        company: "Capgemini"
        companyUrl: "https://www.capgemini.com/es-es/"
        date: "Feb 2021 - Aug 2021"
        featuredLink:
          enable: true
          url: "https://www.capgemini.com/es-es/client-story/sncf-reseau-and-capgemini-set-up-a-surveillance-and-supervision-program-for-the-rail-network/"
        info:
          enable: true
          content: I worked as a DevOps engineer for more than 6 months. 
        content: |
          -	CI/CD pipeline construction.
          -	Automatic provisioning of infrastructure in the AWS cloud, such as (EC2, VPC, S3) using Terraform.
          -	Integration of various DevOps full-cycle tools such as Docker, SonarQube, Ansible, Terraform, AWS, and Zabbix, using Jenkins (Groovy, YAML).
          -	Provisioning using Ansible for low-power devices such as Raspberry Pi.
          -	Metric Generation using Zabbix.
          -	Building flexible and replicable test environments using Vagrant, Docker, and VirtualBox.
          -	Scripting in Windows using NSIS, PowerShell, Batch.
          -	Collaborated with Capgemini-Nantes international team.

      - job: "Coast-Lifeguard"
        company: "Cruz Roja"
        companyUrl: "https://www.cruzroja.es/principal/web/cruz-roja/territorial?centro=15672"
        date: "June 2019 - Sept 2021"
        featuredLink:
          enable: true
          content: It started as a summer job, and I ended up leading a small team of lifeguards. I continue to volunteer for various activities .
        content: |
           A volunteer experience that helped me to put into practice skills such as good communication, responsibility, trust, cooperation, efficient administration of resources and management of a workgroup, in a context of high danger in which it is necessary to deal with the management of high-stress situations.

  # Education
  education:
    enable: true
    # index: true
    items:
      - title: "Master's Degree in Cloud and High-Performance Computing"
        school:
          name: "Polytechnic University of Valencia (UPV)"
          url: "https://www.upv.es/titulaciones/MUCPD/"
        date: "Sept 2021 - Present"
        content: |-
          -	In summary it has allowed me to get a more advanced view of the platforms, tools, technologies, and architectures used for the deployment of elastic and scalable applications in the cloud.
      
      - title: "Computer Engineering Degree"
        school:
          name: "Murcia University"
          url: "https://www.um.es/web/informatica/"
        date: "Sept 2017 - June 2021"
        content: |-
         Honorable mention in:
          - Development Of Information Systems
          - Management Of Technological Innovation In Organizations
          - Management Information Systems
          - End Of Degree Project
        featuredLink:
          enable: true
          name: "Official title"
          url: "https://drive.google.com/file/d/1IPIlydXUH3ebsO1Y4zNHGdIyJJ4ZH8lS/view?usp=sharing"

  # Achievements
  Licenses & certifications:
    enable: true
    items:
      - title: Microsoft Certified Azure Fundamentals
        content: Foundational level knowledge of cloud services and how those services are provided with Microsoft Azure.
        url: https://www.credly.com/badges/100b7e03-9b0b-4156-9cba-0126fbacd97e?source=linked_in_profile
      - title: DAY[EMPRENDE]
        content: DAY EMPRENDE is an innovation day where ideas are shared with the university community.
        url: https://sede.upv.es/oficina_tactica/?idioma=es_ES#/rex/eVerificador?codigoVerificacion=FCP3NQU3Y1I
      - title: Docker Mastery with Kubernetes +Swarm from a Docker Captain
        content: A very good course on the basics of Docker and Kubernetes.
        url: https://sede.upv.es/oficina_tactica/?idioma=es_ES#/rex/eVerificador?codigoVerificacion=FCP3NQU3Y1I

  # projects
  projects:
    enable: true
    items:
      - title: Hugo Profile
        content: A highly customizable and mobile first Hugo template for personal portfolio and blog.
        image: /images/projects/profile.png
        featured:
          name: Demo
          link: https://hugo-profile.netlify.app
        # badges:
        #   - "Hugo"
        #   - "Bootstrap"
        #   - "Javascript"
        links:
          - icon: fa fa-envelope
            url: mailto:?subject=Hugo%20Profile%20Template&body=Check%20it%20out:%20https%3a%2f%2fhugo-profile.netlify.app%2fblog%2fmarkdown-syntax%2f
          - icon: fab fa-github
            url: https://github.com/gurusabarish/hugo-profile
          - icon: fab fa-twitter
            url: https://twitter.com/intent/tweet?text=Check+it+out:&url=https%3A%2F%2Fgithub.com%2Fgurusabarish%2Fhugo-profile

      - title: Image Converter
        content: A web app to convert image to pdf, png to jpg, png to jpg and png to webp without database using django.
        image: /images/projects/converter.jpg
        featured:
          name: Demo
          link: https://django-converter.herokuapp.com
        # badges:
        #   - "Django"
        #   - "Bootstrap"
        links:
          - icon: fab fa-github
            url: https://github.com/gurusabarish/converter

      - title: Hugo Profile V2
        content: A clean and simple Hugo template for personal portfolio and blog.
        image: /images/projects/profile2.jpg
        featured:
          name: Demo V2
          link: https://hugo-profile-2.netlify.app
        # badges:
        #   - "Hugo"
        #   - "Bootstrap"
        #   - "Javascript"
        links:
          - icon: fab fa-github
            url: https://github.com/gurusabarish/HugoProfileV2

  #Contact
  contact:
    enable: true
    content: My inbox is always open. Whether you have a question or just want to say hi, Iâ€™ll try my best to get back to you!
    email: diegotoro1998@gmail.com
    btnName: Mail me

  footer:
    # recentPosts: false
    socialNetworks:
      github: https://github.com/toromuu
      linkedin: https://www.linkedin.com/in/diego-a-t-04726516b/

