baseURL: "https://toromuu.netlify.app"
languageCode: "en-us"
title: "Diego A. Toro Ramirez"
theme: hugo-profile

Paginate: 3
disqusShortname: toromuu
googleAnalytics: G-DWJJVE27WD

markup:
  goldmark:
    renderer:
      unsafe: true


params:
  title: "Diego A. Toro Ramirez"
  description: Welcome to my personal Website
  # staticPath: ""  # The path to serve the static files from
  favicon: "/fav.png"

  theme:
    disableThemeToggle: false
    # defaultTheme: "light" # dark

  # font:
  #   fontSize: 1.5rem # default: 1rem
  #   fontWeight: 500 # default: 400
  #   lineHeight: 1 # default: 1.5
  #   textAlign: right # default: left

  # color preference
  # color:
  #   textColor:
  #   secondaryTextColor:
  #   backgroundColor:
  #   secondaryBackgroundColor:
  #   primaryColor:
  #   secondaryColor:

  #   darkmode:
  #     textColor:
  #     secondaryTextColor:
  #     backgroundColor:
  #     secondaryBackgroundColor:
  #     primaryColor:
  #     secondaryColor:

  # If you want to customize the menu, you can change it here
  # navbar:
  #   align: mx-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
  #   brandLogo: "/logo.png" # Logo for the brand | default is the favicon variable
  #   brandName: "Profile" # Brand name for the brand | default is the title variable

  #   menus:
  #     disableAbout: true
  #     disableExperience: true
  #     disableEducation: true
  #     disableProjects: true
  #     disableAchievements: true
  #     disableContact: true

  # Hero
  hero:
    enable: true
    intro: "Hi, my name is"
    title: "Diego A. Toro Ramirez"
    subtitle: "I build infraestructure in the cloud ☁️"
    content: "I am a DevOps Engineer with a passion for Cloud and Automatition."
    image: /images/hero.jpg
    button:
      enable: true
      name: "Resume"
      url: "#"
    socialLinks:
      fontAwesomeIcons:
        - icon: fab fa-github
          url: https://github.com/toromuu
        - icon: fab fa-gitlab
          url: https://gitlab.com/toromuu
        - icon: fab fa-linkedin
          url: https://www.linkedin.com/in/diego-a-t-04726516b/

          

  # About
  about:
    enable: true
    title: "About Me"
    image: "/images/me.jpg"
    content: |-
      Hi! I am an enthusiast of this new era of technological innovations.
      I have a background in computer science and I am currently finishing a master's degree in cloud computing and high performance in Valencia.
      I am at a stage in my life where I have ambition to learn by putting into practice all my knowledge, innovate and develop solutions that change people's lives.
    
    skills:
      enable: true
      title: "Here are a few technologies I've been working with recently:"
      items:
        - "Kubernetes"
        - "Docker"
        - "Ansible"
        - "Terraform"
        - "AWS"
        - "Jenkins"
        - "Bash"
        - "PowerShell"
        - "VirtualBox"
        - "Vagrant"

  # Experience
  experience:
    enable: true
    items:
      - job: "DevOps Engineer"
        company: "Capgemini"
        companyUrl: "https://www.capgemini.com/es-es/"
        date: "Feb 2021 - Aug 2021"
        featuredLink:
          enable: true
          name: "website"
          url: "https://www.capgemini.com/es-es/client-story/sncf-reseau-and-capgemini-set-up-a-surveillance-and-supervision-program-for-the-rail-network/"
        info:
          enable: true
          content: I worked as a DevOps engineer for more than 6 months. 
        content: |
          -	CI/CD pipeline construction.
          -	Automatic provisioning of infrastructure in the AWS cloud, such as (EC2, VPC, S3) using Terraform.
          -	Integration of various DevOps full-cycle tools such as Docker, SonarQube, Ansible, Terraform, AWS, and Zabbix, using Jenkins (Groovy, YAML).
          -	Provisioning using Ansible for low-power devices such as Raspberry Pi.
          -	Metric Generation using Zabbix.
          -	Building flexible and replicable test environments using Vagrant, Docker, and VirtualBox.
          -	Scripting in Windows using NSIS, PowerShell, Batch.
          -	Collaborated with Capgemini-Nantes international team.

      - job: "Coast-Lifeguard"
        company: "Cruz Roja"
        companyUrl: "https://www2.cruzroja.es/"
        date: "June 2019 - Sept 2021"
        featuredLink:
          enable: true
          name: "website"
          url: "https://www.cruzroja.es/principal/web/cruz-roja/territorial?centro=15672"
        content: |
           A volunteer experience that helped me to put into practice skills such as good communication, responsibility, trust, cooperation, efficient administration of resources and management of a workgroup, in a context of high danger in which it is necessary to deal with the management of high-stress situations.It started as a summer job, and I ended up leading a small team of lifeguards. I continue to volunteer for various activities .

  # Education
  education:
    enable: true
    # index: true
    items:
      - title: "Master's Degree in Cloud and High-Performance Computing"
        school:
          name: "Polytechnic University of Valencia (UPV)"
          url: "https://www.upv.es/titulaciones/MUCPD/"
        date: "Sept 2021 - Present"
        content: |-
          -	In summary it has allowed me to get a more advanced view of the platforms, tools, technologies, and architectures used for the deployment of elastic and scalable applications in the cloud.
      
      - title: "Computer Engineering Degree"
        school:
          name: "Murcia University"
          url: "https://www.um.es/web/informatica/"
        date: "Sept 2017 - June 2021"
        content: |-
         Honorable mention in:
          - Development Of Information Systems
          - Management Of Technological Innovation In Organizations
          - Management Information Systems
          - End Of Degree Project
        featuredLink:
          enable: true
          name: "Official title"
          url: "https://drive.google.com/file/d/1IPIlydXUH3ebsO1Y4zNHGdIyJJ4ZH8lS/view?usp=sharing"

  # Achievements
  achievements:
    enable: true
    items:
      - title: Microsoft Certified Azure Fundamentals
        content: Foundational level knowledge of cloud services and how those services are provided with Microsoft Azure.
        url: https://www.credly.com/badges/100b7e03-9b0b-4156-9cba-0126fbacd97e?source=linked_in_profile
      - title: DAY[EMPRENDE]
        content: DAY EMPRENDE is an innovation day where ideas are shared with the university community.
        url: https://sede.upv.es/oficina_tactica/?idioma=es_ES#/rex/eVerificador?codigoVerificacion=FCP3NQU3Y1I
      - title: Docker Mastery with Kubernetes +Swarm from a Docker Captain
        content: A very good course on the basics of Docker and Kubernetes.
        url: https://sede.upv.es/oficina_tactica/?idioma=es_ES#/rex/eVerificador?codigoVerificacion=FCP3NQU3Y1I

  # projects
  projects:
    enable: true
    items:
      - title: OVERLAY
        content: It is used to deploy a network of linux containers. It allows to understand how container networks work in detail. One of the mechanisms used by container systems such as Docker is the separation of namespaces, so that each container receives its own namespace for each of the named resources it has access to in the OS. Of special relevance is the network namespace, as it is not possible to properly isolate a container if it is allowed to communicate arbitrarily with any other agent in a distributed system. Containers in Linux use network namespaces to establish proper network isolation.
        image: /images/projects/Scenario.png
        featured:
          name: Repository
          link: https://gitlab.com/toromuu/overlay
          badges:
           - "Vagrant"
           - "Linux"
           - "Docker"
           - "Networks"
        links:
          - icon: fab fa-gitlab
            url: https://gitlab.com/toromuu/overlay

      - title: RaspberryPi-Ansible-Test-Environment
        content: A virtualized test environment where you can test your ansible playbooks on 3 full ARM based Raspberry Pi virtual machines. The project has the following architecture, where we have a container with everything necessary to run the ansible playbooks and three other Raspberry Pi containers that will be the target of the playbooks.
        image: /images/projects/Raspberry.png
        featured:
          name: Repository
          link: https://github.com/toromuu/RaspberryPi-Ansible-Test-Environment
          badges:
           - "Docker"
           - "Ansible"
           - "Raspberry PI"
        links:
          - icon: fab fa-gitlab
            url: https://github.com/toromuu/RaspberryPi-Ansible-Test-Environment
    
      - title: Pipeline CI/CD Template
        content: The project tries to cover almost all the theoretical stages of a CI/CD pipeline, starting the development in a Docker container where you will be guaranteed to be working under an identical environment for all developers. Any change made in the repository will trigger the execution of the pipeline itself. The pipeline, the different phases of the automation of the continuous integration and deployment process, will be defined and coordinated through the Jenkins tool, which is installed in a second Docker container. After receiving the change in the repository, unit tests will be executed and the quality of the code will be measured using the Sonarqube tool. Once the code has passed the testing phase, the Terraform tool will be used to provide the infrastructure for the deployment of the application, this being an instance on AWS. After contracting the server, using the Ansible tool, the server will be prepared for the deployment of the application, configuring everything necessary for the application to run. On this web server, the application will be executed and the client will be able to access it as a service from a public ip address.
        image: /images/projects/Arquitecture.png
        featured:
          name: Repository
          link: https://github.com/toromuu/PipelineTemplate
          badges:
           - "Docker"
           - "Ansible"
           - "Terraform"
           - "Jenkins"
           - "CI/CD"
        links:
          - icon: fab fa-github
            url: https://github.com/toromuu/PipelineTemplate
      
      - title: Terraform web-mail infraestructure
        content: A project to deploy through Terraform an infrastructure in AWS to deploy a webmail service.
        image: /images/projects/Diagram.png
        featured:
          name: Repository
          link: https://github.com/albmarti/icp-project
          badges:
           - "Terraform"
           - "AWS"
        links:
          - icon: fab fa-github
            url: https://github.com/albmarti/icp-project

      - title: Terraform web-mail infraestructure
        content: Kumori Platform is a service to automate the complete SaaS software life cycle. This example shows how to build and deploy a Kumori Service Application composed of four components. The repository contains both the manifests needed to deploy the Characters Store Service Application within a Kumori Platorm, and the source code used to build the docker images of the four components. Characters Store Service Application exposes a REST API with a functions to retrieve and store characters.
        image: /images/projects/Kumori.png
        featured:
          name: Repository
          link: https://gitlab.com/toromuu/servicio-en-paas-mariano-diego
          badges:
           - "Kumori"
           - "PaaS"
        links:
          - icon: fab fa-gitlab
            url: https://gitlab.com/toromuu/servicio-en-paas-mariano-diego

  #Contact
  contact:
    enable: true
    content: My inbox is always open. Whether you have a question or just want to say hi, I’ll try my best to get back to you!
    email: diegotoro1998@gmail.com
    btnName: Mail me

  footer:
    # recentPosts: false
    socialNetworks:
      github: https://github.com/toromuu
      gitlab: https://gitlab.com/toromuu
      linkedin: https://www.linkedin.com/in/diego-a-t-04726516b/

